brew "llvm"
brew "gcc"

brew "openssl"
brew "readline"

brew "bash"
brew "zsh"
brew "coreutils"
brew "jq" # https://stedolan.github.io/jq/
brew "gnu-sed"
brew "curl"

brew "vim"
brew "neovim"
brew "asdf"
brew "htop"
brew "ripgrep"
brew "hub"

cask "homebrew/cask-fonts/font-sauce-code-pro-nerd-font"

brew "derailed/k9s/k9s"
