brew "llvm"
brew "gcc"

brew "openssl"
brew "readline"

brew "coreutils"
brew "jq" # https://stedolan.github.io/jq/
brew "gnu-sed"

brew "vim"
brew "neovim"
brew "asdf"
brew "htop"
brew "ripgrep"

tap "homebrew/cask-fonts"
cask "font-sauce-code-pro-nerd-font"
